// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Prefer environment variables for flexibility across environments
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://api.arzansite.com";
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  // Keep defaults for realtime/db; we don't open sockets unless used, but
  // correct anon key ensures any future realtime usage authenticates properly.
});